approvals:
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - "zalando"
          - "zalando-incubator"
X-Zalando-Team: "payana"
# type should be one of [code, doc, config, tools, secrets]
X-Zalando-Type: code
